var pokemonAccentMap = {
  'â': 'a',
  'ä': 'a',
  'ß': 's',
  'Ü': 'u',
  'ü': 'u',
  'Ï': 'i',
  'ï': 'i',
  'Ê': 'e',
  'ê': 'e',
  'é': 'e',
  'È': 'e',
  'è': 'e',
  '-': ' ',
}

function removeAccents(s) {
  if (!s) {
    return '';
  }
  var ret = '';
  for (var i = 0; i < s.length; i++) {
    ret += pokemonAccentMap[s.charAt(i)] || s.charAt(i);
  }
  return ret;
};

var pokemonNames = [{
  "name": "bulbasaur",
  "number": 1
}, {
  "name": "ivysaur",
  "number": 2
}, {
  "name": "venusaur",
  "number": 3
}, {
  "name": "charmander",
  "number": 4
}, {
  "name": "charmeleon",
  "number": 5
}, {
  "name": "charizard",
  "number": 6
}, {
  "name": "squirtle",
  "number": 7
}, {
  "name": "wartortle",
  "number": 8
}, {
  "name": "blastoise",
  "number": 9
}, {
  "name": "caterpie",
  "number": 10
}, {
  "name": "metapod",
  "number": 11
}, {
  "name": "butterfree",
  "number": 12
}, {
  "name": "weedle",
  "number": 13
}, {
  "name": "kakuna",
  "number": 14
}, {
  "name": "beedrill",
  "number": 15
}, {
  "name": "pidgey",
  "number": 16
}, {
  "name": "pidgeotto",
  "number": 17
}, {
  "name": "pidgeot",
  "number": 18
}, {
  "name": "rattata",
  "number": 19
}, {
  "name": "raticate",
  "number": 20
}, {
  "name": "spearow",
  "number": 21
}, {
  "name": "fearow",
  "number": 22
}, {
  "name": "ekans",
  "number": 23
}, {
  "name": "arbok",
  "number": 24
}, {
  "name": "pikachu",
  "number": 25
}, {
  "name": "raichu",
  "number": 26
}, {
  "name": "sandshrew",
  "number": 27
}, {
  "name": "sandslash",
  "number": 28
}, {
  "name": "nidoran-f",
  "number": 29
}, {
  "name": "nidorina",
  "number": 30
}, {
  "name": "nidoqueen",
  "number": 31
}, {
  "name": "nidoran-m",
  "number": 32
}, {
  "name": "nidorino",
  "number": 33
}, {
  "name": "nidoking",
  "number": 34
}, {
  "name": "clefairy",
  "number": 35
}, {
  "name": "clefable",
  "number": 36
}, {
  "name": "vulpix",
  "number": 37
}, {
  "name": "ninetales",
  "number": 38
}, {
  "name": "jigglypuff",
  "number": 39
}, {
  "name": "wigglytuff",
  "number": 40
}, {
  "name": "zubat",
  "number": 41
}, {
  "name": "golbat",
  "number": 42
}, {
  "name": "oddish",
  "number": 43
}, {
  "name": "gloom",
  "number": 44
}, {
  "name": "vileplume",
  "number": 45
}, {
  "name": "paras",
  "number": 46
}, {
  "name": "parasect",
  "number": 47
}, {
  "name": "venonat",
  "number": 48
}, {
  "name": "venomoth",
  "number": 49
}, {
  "name": "diglett",
  "number": 50
}, {
  "name": "dugtrio",
  "number": 51
}, {
  "name": "meowth",
  "number": 52
}, {
  "name": "persian",
  "number": 53
}, {
  "name": "psyduck",
  "number": 54
}, {
  "name": "golduck",
  "number": 55
}, {
  "name": "mankey",
  "number": 56
}, {
  "name": "primeape",
  "number": 57
}, {
  "name": "growlithe",
  "number": 58
}, {
  "name": "arcanine",
  "number": 59
}, {
  "name": "poliwag",
  "number": 60
}, {
  "name": "poliwhirl",
  "number": 61
}, {
  "name": "poliwrath",
  "number": 62
}, {
  "name": "abra",
  "number": 63
}, {
  "name": "kadabra",
  "number": 64
}, {
  "name": "alakazam",
  "number": 65
}, {
  "name": "machop",
  "number": 66
}, {
  "name": "machoke",
  "number": 67
}, {
  "name": "machamp",
  "number": 68
}, {
  "name": "bellsprout",
  "number": 69
}, {
  "name": "weepinbell",
  "number": 70
}, {
  "name": "victreebel",
  "number": 71
}, {
  "name": "tentacool",
  "number": 72
}, {
  "name": "tentacruel",
  "number": 73
}, {
  "name": "geodude",
  "number": 74
}, {
  "name": "graveler",
  "number": 75
}, {
  "name": "golem",
  "number": 76
}, {
  "name": "ponyta",
  "number": 77
}, {
  "name": "rapidash",
  "number": 78
}, {
  "name": "slowpoke",
  "number": 79
}, {
  "name": "slowbro",
  "number": 80
}, {
  "name": "magnemite",
  "number": 81
}, {
  "name": "magneton",
  "number": 82
}, {
  "name": "farfetchd",
  "number": 83
}, {
  "name": "doduo",
  "number": 84
}, {
  "name": "dodrio",
  "number": 85
}, {
  "name": "seel",
  "number": 86
}, {
  "name": "dewgong",
  "number": 87
}, {
  "name": "grimer",
  "number": 88
}, {
  "name": "muk",
  "number": 89
}, {
  "name": "shellder",
  "number": 90
}, {
  "name": "cloyster",
  "number": 91
}, {
  "name": "gastly",
  "number": 92
}, {
  "name": "haunter",
  "number": 93
}, {
  "name": "gengar",
  "number": 94
}, {
  "name": "onix",
  "number": 95
}, {
  "name": "drowzee",
  "number": 96
}, {
  "name": "hypno",
  "number": 97
}, {
  "name": "krabby",
  "number": 98
}, {
  "name": "kingler",
  "number": 99
}, {
  "name": "voltorb",
  "number": 100
}, {
  "name": "electrode",
  "number": 101
}, {
  "name": "exeggcute",
  "number": 102
}, {
  "name": "exeggutor",
  "number": 103
}, {
  "name": "cubone",
  "number": 104
}, {
  "name": "marowak",
  "number": 105
}, {
  "name": "hitmonlee",
  "number": 106
}, {
  "name": "hitmonchan",
  "number": 107
}, {
  "name": "lickitung",
  "number": 108
}, {
  "name": "koffing",
  "number": 109
}, {
  "name": "weezing",
  "number": 110
}, {
  "name": "rhyhorn",
  "number": 111
}, {
  "name": "rhydon",
  "number": 112
}, {
  "name": "chansey",
  "number": 113
}, {
  "name": "tangela",
  "number": 114
}, {
  "name": "kangaskhan",
  "number": 115
}, {
  "name": "horsea",
  "number": 116
}, {
  "name": "seadra",
  "number": 117
}, {
  "name": "goldeen",
  "number": 118
}, {
  "name": "seaking",
  "number": 119
}, {
  "name": "staryu",
  "number": 120
}, {
  "name": "starmie",
  "number": 121
}, {
  "name": "mr-mime",
  "number": 122
}, {
  "name": "scyther",
  "number": 123
}, {
  "name": "jynx",
  "number": 124
}, {
  "name": "electabuzz",
  "number": 125
}, {
  "name": "magmar",
  "number": 126
}, {
  "name": "pinsir",
  "number": 127
}, {
  "name": "tauros",
  "number": 128
}, {
  "name": "magikarp",
  "number": 129
}, {
  "name": "gyarados",
  "number": 130
}, {
  "name": "lapras",
  "number": 131
}, {
  "name": "ditto",
  "number": 132
}, {
  "name": "eevee",
  "number": 133
}, {
  "name": "vaporeon",
  "number": 134
}, {
  "name": "jolteon",
  "number": 135
}, {
  "name": "flareon",
  "number": 136
}, {
  "name": "porygon",
  "number": 137
}, {
  "name": "omanyte",
  "number": 138
}, {
  "name": "omastar",
  "number": 139
}, {
  "name": "kabuto",
  "number": 140
}, {
  "name": "kabutops",
  "number": 141
}, {
  "name": "aerodactyl",
  "number": 142
}, {
  "name": "snorlax",
  "number": 143
}, {
  "name": "articuno",
  "number": 144
}, {
  "name": "zapdos",
  "number": 145
}, {
  "name": "moltres",
  "number": 146
}, {
  "name": "dratini",
  "number": 147
}, {
  "name": "dragonair",
  "number": 148
}, {
  "name": "dragonite",
  "number": 149
}, {
  "name": "mewtwo",
  "number": 150
}, {
  "name": "mew",
  "number": 151
}, {
  "name": "chikorita",
  "number": 152
}, {
  "name": "bayleef",
  "number": 153
}, {
  "name": "meganium",
  "number": 154
}, {
  "name": "cyndaquil",
  "number": 155
}, {
  "name": "quilava",
  "number": 156
}, {
  "name": "typhlosion",
  "number": 157
}, {
  "name": "totodile",
  "number": 158
}, {
  "name": "croconaw",
  "number": 159
}, {
  "name": "feraligatr",
  "number": 160
}, {
  "name": "sentret",
  "number": 161
}, {
  "name": "furret",
  "number": 162
}, {
  "name": "hoothoot",
  "number": 163
}, {
  "name": "noctowl",
  "number": 164
}, {
  "name": "ledyba",
  "number": 165
}, {
  "name": "ledian",
  "number": 166
}, {
  "name": "spinarak",
  "number": 167
}, {
  "name": "ariados",
  "number": 168
}, {
  "name": "crobat",
  "number": 169
}, {
  "name": "chinchou",
  "number": 170
}, {
  "name": "lanturn",
  "number": 171
}, {
  "name": "pichu",
  "number": 172
}, {
  "name": "cleffa",
  "number": 173
}, {
  "name": "igglybuff",
  "number": 174
}, {
  "name": "togepi",
  "number": 175
}, {
  "name": "togetic",
  "number": 176
}, {
  "name": "natu",
  "number": 177
}, {
  "name": "xatu",
  "number": 178
}, {
  "name": "mareep",
  "number": 179
}, {
  "name": "flaaffy",
  "number": 180
}, {
  "name": "ampharos",
  "number": 181
}, {
  "name": "bellossom",
  "number": 182
}, {
  "name": "marill",
  "number": 183
}, {
  "name": "azumarill",
  "number": 184
}, {
  "name": "sudowoodo",
  "number": 185
}, {
  "name": "politoed",
  "number": 186
}, {
  "name": "hoppip",
  "number": 187
}, {
  "name": "skiploom",
  "number": 188
}, {
  "name": "jumpluff",
  "number": 189
}, {
  "name": "aipom",
  "number": 190
}, {
  "name": "sunkern",
  "number": 191
}, {
  "name": "sunflora",
  "number": 192
}, {
  "name": "yanma",
  "number": 193
}, {
  "name": "wooper",
  "number": 194
}, {
  "name": "quagsire",
  "number": 195
}, {
  "name": "espeon",
  "number": 196
}, {
  "name": "umbreon",
  "number": 197
}, {
  "name": "murkrow",
  "number": 198
}, {
  "name": "slowking",
  "number": 199
}, {
  "name": "misdreavus",
  "number": 200
}, {
  "name": "unown",
  "number": 201
}, {
  "name": "wobbuffet",
  "number": 202
}, {
  "name": "girafarig",
  "number": 203
}, {
  "name": "pineco",
  "number": 204
}, {
  "name": "forretress",
  "number": 205
}, {
  "name": "dunsparce",
  "number": 206
}, {
  "name": "gligar",
  "number": 207
}, {
  "name": "steelix",
  "number": 208
}, {
  "name": "snubbull",
  "number": 209
}, {
  "name": "granbull",
  "number": 210
}, {
  "name": "qwilfish",
  "number": 211
}, {
  "name": "scizor",
  "number": 212
}, {
  "name": "shuckle",
  "number": 213
}, {
  "name": "heracross",
  "number": 214
}, {
  "name": "sneasel",
  "number": 215
}, {
  "name": "teddiursa",
  "number": 216
}, {
  "name": "ursaring",
  "number": 217
}, {
  "name": "slugma",
  "number": 218
}, {
  "name": "magcargo",
  "number": 219
}, {
  "name": "swinub",
  "number": 220
}, {
  "name": "piloswine",
  "number": 221
}, {
  "name": "corsola",
  "number": 222
}, {
  "name": "remoraid",
  "number": 223
}, {
  "name": "octillery",
  "number": 224
}, {
  "name": "delibird",
  "number": 225
}, {
  "name": "mantine",
  "number": 226
}, {
  "name": "skarmory",
  "number": 227
}, {
  "name": "houndour",
  "number": 228
}, {
  "name": "houndoom",
  "number": 229
}, {
  "name": "kingdra",
  "number": 230
}, {
  "name": "phanpy",
  "number": 231
}, {
  "name": "donphan",
  "number": 232
}, {
  "name": "porygon2",
  "number": 233
}, {
  "name": "stantler",
  "number": 234
}, {
  "name": "smeargle",
  "number": 235
}, {
  "name": "tyrogue",
  "number": 236
}, {
  "name": "hitmontop",
  "number": 237
}, {
  "name": "smoochum",
  "number": 238
}, {
  "name": "elekid",
  "number": 239
}, {
  "name": "magby",
  "number": 240
}, {
  "name": "miltank",
  "number": 241
}, {
  "name": "blissey",
  "number": 242
}, {
  "name": "raikou",
  "number": 243
}, {
  "name": "entei",
  "number": 244
}, {
  "name": "suicune",
  "number": 245
}, {
  "name": "larvitar",
  "number": 246
}, {
  "name": "pupitar",
  "number": 247
}, {
  "name": "tyranitar",
  "number": 248
}, {
  "name": "lugia",
  "number": 249
}, {
  "name": "ho-oh",
  "number": 250
}, {
  "name": "celebi",
  "number": 251
}, {
  "name": "treecko",
  "number": 252
}, {
  "name": "grovyle",
  "number": 253
}, {
  "name": "sceptile",
  "number": 254
}, {
  "name": "torchic",
  "number": 255
}, {
  "name": "combusken",
  "number": 256
}, {
  "name": "blaziken",
  "number": 257
}, {
  "name": "mudkip",
  "number": 258
}, {
  "name": "marshtomp",
  "number": 259
}, {
  "name": "swampert",
  "number": 260
}, {
  "name": "poochyena",
  "number": 261
}, {
  "name": "mightyena",
  "number": 262
}, {
  "name": "zigzagoon",
  "number": 263
}, {
  "name": "linoone",
  "number": 264
}, {
  "name": "wurmple",
  "number": 265
}, {
  "name": "silcoon",
  "number": 266
}, {
  "name": "beautifly",
  "number": 267
}, {
  "name": "cascoon",
  "number": 268
}, {
  "name": "dustox",
  "number": 269
}, {
  "name": "lotad",
  "number": 270
}, {
  "name": "lombre",
  "number": 271
}, {
  "name": "ludicolo",
  "number": 272
}, {
  "name": "seedot",
  "number": 273
}, {
  "name": "nuzleaf",
  "number": 274
}, {
  "name": "shiftry",
  "number": 275
}, {
  "name": "taillow",
  "number": 276
}, {
  "name": "swellow",
  "number": 277
}, {
  "name": "wingull",
  "number": 278
}, {
  "name": "pelipper",
  "number": 279
}, {
  "name": "ralts",
  "number": 280
}, {
  "name": "kirlia",
  "number": 281
}, {
  "name": "gardevoir",
  "number": 282
}, {
  "name": "surskit",
  "number": 283
}, {
  "name": "masquerain",
  "number": 284
}, {
  "name": "shroomish",
  "number": 285
}, {
  "name": "breloom",
  "number": 286
}, {
  "name": "slakoth",
  "number": 287
}, {
  "name": "vigoroth",
  "number": 288
}, {
  "name": "slaking",
  "number": 289
}, {
  "name": "nincada",
  "number": 290
}, {
  "name": "ninjask",
  "number": 291
}, {
  "name": "shedinja",
  "number": 292
}, {
  "name": "whismur",
  "number": 293
}, {
  "name": "loudred",
  "number": 294
}, {
  "name": "exploud",
  "number": 295
}, {
  "name": "makuhita",
  "number": 296
}, {
  "name": "hariyama",
  "number": 297
}, {
  "name": "azurill",
  "number": 298
}, {
  "name": "nosepass",
  "number": 299
}, {
  "name": "skitty",
  "number": 300
}, {
  "name": "delcatty",
  "number": 301
}, {
  "name": "sableye",
  "number": 302
}, {
  "name": "mawile",
  "number": 303
}, {
  "name": "aron",
  "number": 304
}, {
  "name": "lairon",
  "number": 305
}, {
  "name": "aggron",
  "number": 306
}, {
  "name": "meditite",
  "number": 307
}, {
  "name": "medicham",
  "number": 308
}, {
  "name": "electrike",
  "number": 309
}, {
  "name": "manectric",
  "number": 310
}, {
  "name": "plusle",
  "number": 311
}, {
  "name": "minun",
  "number": 312
}, {
  "name": "volbeat",
  "number": 313
}, {
  "name": "illumise",
  "number": 314
}, {
  "name": "roselia",
  "number": 315
}, {
  "name": "gulpin",
  "number": 316
}, {
  "name": "swalot",
  "number": 317
}, {
  "name": "carvanha",
  "number": 318
}, {
  "name": "sharpedo",
  "number": 319
}, {
  "name": "wailmer",
  "number": 320
}, {
  "name": "wailord",
  "number": 321
}, {
  "name": "numel",
  "number": 322
}, {
  "name": "camerupt",
  "number": 323
}, {
  "name": "torkoal",
  "number": 324
}, {
  "name": "spoink",
  "number": 325
}, {
  "name": "grumpig",
  "number": 326
}, {
  "name": "spinda",
  "number": 327
}, {
  "name": "trapinch",
  "number": 328
}, {
  "name": "vibrava",
  "number": 329
}, {
  "name": "flygon",
  "number": 330
}, {
  "name": "cacnea",
  "number": 331
}, {
  "name": "cacturne",
  "number": 332
}, {
  "name": "swablu",
  "number": 333
}, {
  "name": "altaria",
  "number": 334
}, {
  "name": "zangoose",
  "number": 335
}, {
  "name": "seviper",
  "number": 336
}, {
  "name": "lunatone",
  "number": 337
}, {
  "name": "solrock",
  "number": 338
}, {
  "name": "barboach",
  "number": 339
}, {
  "name": "whiscash",
  "number": 340
}, {
  "name": "corphish",
  "number": 341
}, {
  "name": "crawdaunt",
  "number": 342
}, {
  "name": "baltoy",
  "number": 343
}, {
  "name": "claydol",
  "number": 344
}, {
  "name": "lileep",
  "number": 345
}, {
  "name": "cradily",
  "number": 346
}, {
  "name": "anorith",
  "number": 347
}, {
  "name": "armaldo",
  "number": 348
}, {
  "name": "feebas",
  "number": 349
}, {
  "name": "milotic",
  "number": 350
}, {
  "name": "castform",
  "number": 351
}, {
  "name": "kecleon",
  "number": 352
}, {
  "name": "shuppet",
  "number": 353
}, {
  "name": "banette",
  "number": 354
}, {
  "name": "duskull",
  "number": 355
}, {
  "name": "dusclops",
  "number": 356
}, {
  "name": "tropius",
  "number": 357
}, {
  "name": "chimecho",
  "number": 358
}, {
  "name": "absol",
  "number": 359
}, {
  "name": "wynaut",
  "number": 360
}, {
  "name": "snorunt",
  "number": 361
}, {
  "name": "glalie",
  "number": 362
}, {
  "name": "spheal",
  "number": 363
}, {
  "name": "sealeo",
  "number": 364
}, {
  "name": "walrein",
  "number": 365
}, {
  "name": "clamperl",
  "number": 366
}, {
  "name": "huntail",
  "number": 367
}, {
  "name": "gorebyss",
  "number": 368
}, {
  "name": "relicanth",
  "number": 369
}, {
  "name": "luvdisc",
  "number": 370
}, {
  "name": "bagon",
  "number": 371
}, {
  "name": "shelgon",
  "number": 372
}, {
  "name": "salamence",
  "number": 373
}, {
  "name": "beldum",
  "number": 374
}, {
  "name": "metang",
  "number": 375
}, {
  "name": "metagross",
  "number": 376
}, {
  "name": "regirock",
  "number": 377
}, {
  "name": "regice",
  "number": 378
}, {
  "name": "registeel",
  "number": 379
}, {
  "name": "latias",
  "number": 380
}, {
  "name": "latios",
  "number": 381
}, {
  "name": "kyogre",
  "number": 382
}, {
  "name": "groudon",
  "number": 383
}, {
  "name": "rayquaza",
  "number": 384
}, {
  "name": "jirachi",
  "number": 385
}, {
  "name": "deoxys-normal",
  "number": 386
}, {
  "name": "turtwig",
  "number": 387
}, {
  "name": "grotle",
  "number": 388
}, {
  "name": "torterra",
  "number": 389
}, {
  "name": "chimchar",
  "number": 390
}, {
  "name": "monferno",
  "number": 391
}, {
  "name": "infernape",
  "number": 392
}, {
  "name": "piplup",
  "number": 393
}, {
  "name": "prinplup",
  "number": 394
}, {
  "name": "empoleon",
  "number": 395
}, {
  "name": "starly",
  "number": 396
}, {
  "name": "staravia",
  "number": 397
}, {
  "name": "staraptor",
  "number": 398
}, {
  "name": "bidoof",
  "number": 399
}, {
  "name": "bibarel",
  "number": 400
}, {
  "name": "kricketot",
  "number": 401
}, {
  "name": "kricketune",
  "number": 402
}, {
  "name": "shinx",
  "number": 403
}, {
  "name": "luxio",
  "number": 404
}, {
  "name": "luxray",
  "number": 405
}, {
  "name": "budew",
  "number": 406
}, {
  "name": "roserade",
  "number": 407
}, {
  "name": "cranidos",
  "number": 408
}, {
  "name": "rampardos",
  "number": 409
}, {
  "name": "shieldon",
  "number": 410
}, {
  "name": "bastiodon",
  "number": 411
}, {
  "name": "burmy",
  "number": 412
}, {
  "name": "wormadam-plant",
  "number": 413
}, {
  "name": "mothim",
  "number": 414
}, {
  "name": "combee",
  "number": 415
}, {
  "name": "vespiquen",
  "number": 416
}, {
  "name": "pachirisu",
  "number": 417
}, {
  "name": "buizel",
  "number": 418
}, {
  "name": "floatzel",
  "number": 419
}, {
  "name": "cherubi",
  "number": 420
}, {
  "name": "cherrim",
  "number": 421
}, {
  "name": "shellos",
  "number": 422
}, {
  "name": "gastrodon",
  "number": 423
}, {
  "name": "ambipom",
  "number": 424
}, {
  "name": "drifloon",
  "number": 425
}, {
  "name": "drifblim",
  "number": 426
}, {
  "name": "buneary",
  "number": 427
}, {
  "name": "lopunny",
  "number": 428
}, {
  "name": "mismagius",
  "number": 429
}, {
  "name": "honchkrow",
  "number": 430
}, {
  "name": "glameow",
  "number": 431
}, {
  "name": "purugly",
  "number": 432
}, {
  "name": "chingling",
  "number": 433
}, {
  "name": "stunky",
  "number": 434
}, {
  "name": "skuntank",
  "number": 435
}, {
  "name": "bronzor",
  "number": 436
}, {
  "name": "bronzong",
  "number": 437
}, {
  "name": "bonsly",
  "number": 438
}, {
  "name": "mime-jr",
  "number": 439
}, {
  "name": "happiny",
  "number": 440
}, {
  "name": "chatot",
  "number": 441
}, {
  "name": "spiritomb",
  "number": 442
}, {
  "name": "gible",
  "number": 443
}, {
  "name": "gabite",
  "number": 444
}, {
  "name": "garchomp",
  "number": 445
}, {
  "name": "munchlax",
  "number": 446
}, {
  "name": "riolu",
  "number": 447
}, {
  "name": "lucario",
  "number": 448
}, {
  "name": "hippopotas",
  "number": 449
}, {
  "name": "hippowdon",
  "number": 450
}, {
  "name": "skorupi",
  "number": 451
}, {
  "name": "drapion",
  "number": 452
}, {
  "name": "croagunk",
  "number": 453
}, {
  "name": "toxicroak",
  "number": 454
}, {
  "name": "carnivine",
  "number": 455
}, {
  "name": "finneon",
  "number": 456
}, {
  "name": "lumineon",
  "number": 457
}, {
  "name": "mantyke",
  "number": 458
}, {
  "name": "snover",
  "number": 459
}, {
  "name": "abomasnow",
  "number": 460
}, {
  "name": "weavile",
  "number": 461
}, {
  "name": "magnezone",
  "number": 462
}, {
  "name": "lickilicky",
  "number": 463
}, {
  "name": "rhyperior",
  "number": 464
}, {
  "name": "tangrowth",
  "number": 465
}, {
  "name": "electivire",
  "number": 466
}, {
  "name": "magmortar",
  "number": 467
}, {
  "name": "togekiss",
  "number": 468
}, {
  "name": "yanmega",
  "number": 469
}, {
  "name": "leafeon",
  "number": 470
}, {
  "name": "glaceon",
  "number": 471
}, {
  "name": "gliscor",
  "number": 472
}, {
  "name": "mamoswine",
  "number": 473
}, {
  "name": "porygon-z",
  "number": 474
}, {
  "name": "gallade",
  "number": 475
}, {
  "name": "probopass",
  "number": 476
}, {
  "name": "dusknoir",
  "number": 477
}, {
  "name": "froslass",
  "number": 478
}, {
  "name": "rotom",
  "number": 479
}, {
  "name": "uxie",
  "number": 480
}, {
  "name": "mesprit",
  "number": 481
}, {
  "name": "azelf",
  "number": 482
}, {
  "name": "dialga",
  "number": 483
}, {
  "name": "palkia",
  "number": 484
}, {
  "name": "heatran",
  "number": 485
}, {
  "name": "regigigas",
  "number": 486
}, {
  "name": "giratina-altered",
  "number": 487
}, {
  "name": "cresselia",
  "number": 488
}, {
  "name": "phione",
  "number": 489
}, {
  "name": "manaphy",
  "number": 490
}, {
  "name": "darkrai",
  "number": 491
}, {
  "name": "shaymin-land",
  "number": 492
}, {
  "name": "arceus",
  "number": 493
}, {
  "name": "victini",
  "number": 494
}, {
  "name": "snivy",
  "number": 495
}, {
  "name": "servine",
  "number": 496
}, {
  "name": "serperior",
  "number": 497
}, {
  "name": "tepig",
  "number": 498
}, {
  "name": "pignite",
  "number": 499
}, {
  "name": "emboar",
  "number": 500
}, {
  "name": "oshawott",
  "number": 501
}, {
  "name": "dewott",
  "number": 502
}, {
  "name": "samurott",
  "number": 503
}, {
  "name": "patrat",
  "number": 504
}, {
  "name": "watchog",
  "number": 505
}, {
  "name": "lillipup",
  "number": 506
}, {
  "name": "herdier",
  "number": 507
}, {
  "name": "stoutland",
  "number": 508
}, {
  "name": "purrloin",
  "number": 509
}, {
  "name": "liepard",
  "number": 510
}, {
  "name": "pansage",
  "number": 511
}, {
  "name": "simisage",
  "number": 512
}, {
  "name": "pansear",
  "number": 513
}, {
  "name": "simisear",
  "number": 514
}, {
  "name": "panpour",
  "number": 515
}, {
  "name": "simipour",
  "number": 516
}, {
  "name": "munna",
  "number": 517
}, {
  "name": "musharna",
  "number": 518
}, {
  "name": "pidove",
  "number": 519
}, {
  "name": "tranquill",
  "number": 520
}, {
  "name": "unfezant",
  "number": 521
}, {
  "name": "blitzle",
  "number": 522
}, {
  "name": "zebstrika",
  "number": 523
}, {
  "name": "roggenrola",
  "number": 524
}, {
  "name": "boldore",
  "number": 525
}, {
  "name": "gigalith",
  "number": 526
}, {
  "name": "woobat",
  "number": 527
}, {
  "name": "swoobat",
  "number": 528
}, {
  "name": "drilbur",
  "number": 529
}, {
  "name": "excadrill",
  "number": 530
}, {
  "name": "audino",
  "number": 531
}, {
  "name": "timburr",
  "number": 532
}, {
  "name": "gurdurr",
  "number": 533
}, {
  "name": "conkeldurr",
  "number": 534
}, {
  "name": "tympole",
  "number": 535
}, {
  "name": "palpitoad",
  "number": 536
}, {
  "name": "seismitoad",
  "number": 537
}, {
  "name": "throh",
  "number": 538
}, {
  "name": "sawk",
  "number": 539
}, {
  "name": "sewaddle",
  "number": 540
}, {
  "name": "swadloon",
  "number": 541
}, {
  "name": "leavanny",
  "number": 542
}, {
  "name": "venipede",
  "number": 543
}, {
  "name": "whirlipede",
  "number": 544
}, {
  "name": "scolipede",
  "number": 545
}, {
  "name": "cottonee",
  "number": 546
}, {
  "name": "whimsicott",
  "number": 547
}, {
  "name": "petilil",
  "number": 548
}, {
  "name": "lilligant",
  "number": 549
}, {
  "name": "basculin-red-striped",
  "number": 550
}, {
  "name": "sandile",
  "number": 551
}, {
  "name": "krokorok",
  "number": 552
}, {
  "name": "krookodile",
  "number": 553
}, {
  "name": "darumaka",
  "number": 554
}, {
  "name": "darmanitan-standard",
  "number": 555
}, {
  "name": "maractus",
  "number": 556
}, {
  "name": "dwebble",
  "number": 557
}, {
  "name": "crustle",
  "number": 558
}, {
  "name": "scraggy",
  "number": 559
}, {
  "name": "scrafty",
  "number": 560
}, {
  "name": "sigilyph",
  "number": 561
}, {
  "name": "yamask",
  "number": 562
}, {
  "name": "cofagrigus",
  "number": 563
}, {
  "name": "tirtouga",
  "number": 564
}, {
  "name": "carracosta",
  "number": 565
}, {
  "name": "archen",
  "number": 566
}, {
  "name": "archeops",
  "number": 567
}, {
  "name": "trubbish",
  "number": 568
}, {
  "name": "garbodor",
  "number": 569
}, {
  "name": "zorua",
  "number": 570
}, {
  "name": "zoroark",
  "number": 571
}, {
  "name": "minccino",
  "number": 572
}, {
  "name": "cinccino",
  "number": 573
}, {
  "name": "gothita",
  "number": 574
}, {
  "name": "gothorita",
  "number": 575
}, {
  "name": "gothitelle",
  "number": 576
}, {
  "name": "solosis",
  "number": 577
}, {
  "name": "duosion",
  "number": 578
}, {
  "name": "reuniclus",
  "number": 579
}, {
  "name": "ducklett",
  "number": 580
}, {
  "name": "swanna",
  "number": 581
}, {
  "name": "vanillite",
  "number": 582
}, {
  "name": "vanillish",
  "number": 583
}, {
  "name": "vanilluxe",
  "number": 584
}, {
  "name": "deerling",
  "number": 585
}, {
  "name": "sawsbuck",
  "number": 586
}, {
  "name": "emolga",
  "number": 587
}, {
  "name": "karrablast",
  "number": 588
}, {
  "name": "escavalier",
  "number": 589
}, {
  "name": "foongus",
  "number": 590
}, {
  "name": "amoonguss",
  "number": 591
}, {
  "name": "frillish",
  "number": 592
}, {
  "name": "jellicent",
  "number": 593
}, {
  "name": "alomomola",
  "number": 594
}, {
  "name": "joltik",
  "number": 595
}, {
  "name": "galvantula",
  "number": 596
}, {
  "name": "ferroseed",
  "number": 597
}, {
  "name": "ferrothorn",
  "number": 598
}, {
  "name": "klink",
  "number": 599
}, {
  "name": "klang",
  "number": 600
}, {
  "name": "klinklang",
  "number": 601
}, {
  "name": "tynamo",
  "number": 602
}, {
  "name": "eelektrik",
  "number": 603
}, {
  "name": "eelektross",
  "number": 604
}, {
  "name": "elgyem",
  "number": 605
}, {
  "name": "beheeyem",
  "number": 606
}, {
  "name": "litwick",
  "number": 607
}, {
  "name": "lampent",
  "number": 608
}, {
  "name": "chandelure",
  "number": 609
}, {
  "name": "axew",
  "number": 610
}, {
  "name": "fraxure",
  "number": 611
}, {
  "name": "haxorus",
  "number": 612
}, {
  "name": "cubchoo",
  "number": 613
}, {
  "name": "beartic",
  "number": 614
}, {
  "name": "cryogonal",
  "number": 615
}, {
  "name": "shelmet",
  "number": 616
}, {
  "name": "accelgor",
  "number": 617
}, {
  "name": "stunfisk",
  "number": 618
}, {
  "name": "mienfoo",
  "number": 619
}, {
  "name": "mienshao",
  "number": 620
}, {
  "name": "druddigon",
  "number": 621
}, {
  "name": "golett",
  "number": 622
}, {
  "name": "golurk",
  "number": 623
}, {
  "name": "pawniard",
  "number": 624
}, {
  "name": "bisharp",
  "number": 625
}, {
  "name": "bouffalant",
  "number": 626
}, {
  "name": "rufflet",
  "number": 627
}, {
  "name": "braviary",
  "number": 628
}, {
  "name": "vullaby",
  "number": 629
}, {
  "name": "mandibuzz",
  "number": 630
}, {
  "name": "heatmor",
  "number": 631
}, {
  "name": "durant",
  "number": 632
}, {
  "name": "deino",
  "number": 633
}, {
  "name": "zweilous",
  "number": 634
}, {
  "name": "hydreigon",
  "number": 635
}, {
  "name": "larvesta",
  "number": 636
}, {
  "name": "volcarona",
  "number": 637
}, {
  "name": "cobalion",
  "number": 638
}, {
  "name": "terrakion",
  "number": 639
}, {
  "name": "virizion",
  "number": 640
}, {
  "name": "tornadus-incarnate",
  "number": 641
}, {
  "name": "thundurus-incarnate",
  "number": 642
}, {
  "name": "reshiram",
  "number": 643
}, {
  "name": "zekrom",
  "number": 644
}, {
  "name": "landorus-incarnate",
  "number": 645
}, {
  "name": "kyurem",
  "number": 646
}, {
  "name": "keldeo-ordinary",
  "number": 647
}, {
  "name": "meloetta-aria",
  "number": 648
}, {
  "name": "genesect",
  "number": 649
}, {
  "name": "chespin",
  "number": 650
}, {
  "name": "quilladin",
  "number": 651
}, {
  "name": "chesnaught",
  "number": 652
}, {
  "name": "fennekin",
  "number": 653
}, {
  "name": "braixen",
  "number": 654
}, {
  "name": "delphox",
  "number": 655
}, {
  "name": "froakie",
  "number": 656
}, {
  "name": "frogadier",
  "number": 657
}, {
  "name": "greninja",
  "number": 658
}, {
  "name": "bunnelby",
  "number": 659
}, {
  "name": "diggersby",
  "number": 660
}, {
  "name": "fletchling",
  "number": 661
}, {
  "name": "fletchinder",
  "number": 662
}, {
  "name": "talonflame",
  "number": 663
}, {
  "name": "scatterbug",
  "number": 664
}, {
  "name": "spewpa",
  "number": 665
}, {
  "name": "vivillon",
  "number": 666
}, {
  "name": "litleo",
  "number": 667
}, {
  "name": "pyroar",
  "number": 668
}, {
  "name": "flabébé",
  "number": 669
}, {
  "name": "floette",
  "number": 670
}, {
  "name": "florges",
  "number": 671
}, {
  "name": "skiddo",
  "number": 672
}, {
  "name": "gogoat",
  "number": 673
}, {
  "name": "pancham",
  "number": 674
}, {
  "name": "pangoro",
  "number": 675
}, {
  "name": "furfrou",
  "number": 676
}, {
  "name": "espurr",
  "number": 677
}, {
  "name": "meowstic-male",
  "number": 678
}, {
  "name": "honedge",
  "number": 679
}, {
  "name": "doublade",
  "number": 680
}, {
  "name": "aegislash-shield",
  "number": 681
}, {
  "name": "spritzee",
  "number": 682
}, {
  "name": "aromatisse",
  "number": 683
}, {
  "name": "swirlix",
  "number": 684
}, {
  "name": "slurpuff",
  "number": 685
}, {
  "name": "inkay",
  "number": 686
}, {
  "name": "malamar",
  "number": 687
}, {
  "name": "binacle",
  "number": 688
}, {
  "name": "barbaracle",
  "number": 689
}, {
  "name": "skrelp",
  "number": 690
}, {
  "name": "dragalge",
  "number": 691
}, {
  "name": "clauncher",
  "number": 692
}, {
  "name": "clawitzer",
  "number": 693
}, {
  "name": "helioptile",
  "number": 694
}, {
  "name": "heliolisk",
  "number": 695
}, {
  "name": "tyrunt",
  "number": 696
}, {
  "name": "tyrantrum",
  "number": 697
}, {
  "name": "amaura",
  "number": 698
}, {
  "name": "aurorus",
  "number": 699
}, {
  "name": "sylveon",
  "number": 700
}, {
  "name": "hawlucha",
  "number": 701
}, {
  "name": "dedenne",
  "number": 702
}, {
  "name": "carbink",
  "number": 703
}, {
  "name": "goomy",
  "number": 704
}, {
  "name": "sliggoo",
  "number": 705
}, {
  "name": "goodra",
  "number": 706
}, {
  "name": "klefki",
  "number": 707
}, {
  "name": "phantump",
  "number": 708
}, {
  "name": "trevenant",
  "number": 709
}, {
  "name": "pumpkaboo-average",
  "number": 710
}, {
  "name": "gourgeist-average",
  "number": 711
}, {
  "name": "bergmite",
  "number": 712
}, {
  "name": "avalugg",
  "number": 713
}, {
  "name": "noibat",
  "number": 714
}, {
  "name": "noivern",
  "number": 715
}, {
  "name": "xerneas",
  "number": 716
}, {
  "name": "yveltal",
  "number": 717
}, {
  "name": "zygarde",
  "number": 718
}, {
  "name": "diancie",
  "number": 719
}, {
  "name": "hoopa",
  "number": 720
}, {
  "name": "volcanion",
  "number": 721
}, {
  "name": "rowlet",
  "number": 722
}, {
  "name": "dartrix",
  "number": 723
}, {
  "name": "decidueye",
  "number": 724
}, {
  "name": "litten",
  "number": 725
}, {
  "name": "torracat",
  "number": 726
}, {
  "name": "incineroar",
  "number": 727
}, {
  "name": "popplio",
  "number": 728
}, {
  "name": "brionne",
  "number": 729
}, {
  "name": "primarina",
  "number": 730
}, {
  "name": "pikipek",
  "number": 731
}, {
  "name": "trumbeak",
  "number": 732
}, {
  "name": "toucannon",
  "number": 733
}, {
  "name": "yungoos",
  "number": 734
}, {
  "name": "gumshoos",
  "number": 735
}, {
  "name": "grubbin",
  "number": 736
}, {
  "name": "charjabug",
  "number": 737
}, {
  "name": "vikavolt",
  "number": 738
}, {
  "name": "crabrawler",
  "number": 739
}, {
  "name": "crabominable",
  "number": 740
}, {
  "name": "oricorio-baile",
  "number": 741
}, {
  "name": "cutiefly",
  "number": 742
}, {
  "name": "ribombee",
  "number": 743
}, {
  "name": "rockruff",
  "number": 744
}, {
  "name": "lycanroc-midday",
  "number": 745
}, {
  "name": "wishiwashi-solo",
  "number": 746
}, {
  "name": "mareanie",
  "number": 747
}, {
  "name": "toxapex",
  "number": 748
}, {
  "name": "mudbray",
  "number": 749
}, {
  "name": "mudsdale",
  "number": 750
}, {
  "name": "dewpider",
  "number": 751
}, {
  "name": "araquanid",
  "number": 752
}, {
  "name": "fomantis",
  "number": 753
}, {
  "name": "lurantis",
  "number": 754
}, {
  "name": "morelull",
  "number": 755
}, {
  "name": "shiinotic",
  "number": 756
}, {
  "name": "salandit",
  "number": 757
}, {
  "name": "salazzle",
  "number": 758
}, {
  "name": "stufful",
  "number": 759
}, {
  "name": "bewear",
  "number": 760
}, {
  "name": "bounsweet",
  "number": 761
}, {
  "name": "steenee",
  "number": 762
}, {
  "name": "tsareena",
  "number": 763
}, {
  "name": "comfey",
  "number": 764
}, {
  "name": "oranguru",
  "number": 765
}, {
  "name": "passimian",
  "number": 766
}, {
  "name": "wimpod",
  "number": 767
}, {
  "name": "golisopod",
  "number": 768
}, {
  "name": "sandygast",
  "number": 769
}, {
  "name": "palossand",
  "number": 770
}, {
  "name": "pyukumuku",
  "number": 771
}, {
  "name": "type-null",
  "number": 772
}, {
  "name": "silvally",
  "number": 773
}, {
  "name": "minior-red-meteor",
  "number": 774
}, {
  "name": "komala",
  "number": 775
}, {
  "name": "turtonator",
  "number": 776
}, {
  "name": "togedemaru",
  "number": 777
}, {
  "name": "mimikyu-disguised",
  "number": 778
}, {
  "name": "bruxish",
  "number": 779
}, {
  "name": "drampa",
  "number": 780
}, {
  "name": "dhelmise",
  "number": 781
}, {
  "name": "jangmo-o",
  "number": 782
}, {
  "name": "hakamo-o",
  "number": 783
}, {
  "name": "kommo-o",
  "number": 784
}, {
  "name": "tapu-koko",
  "number": 785
}, {
  "name": "tapu-lele",
  "number": 786
}, {
  "name": "tapu-bulu",
  "number": 787
}, {
  "name": "tapu-fini",
  "number": 788
}, {
  "name": "cosmog",
  "number": 789
}, {
  "name": "cosmoem",
  "number": 790
}, {
  "name": "solgaleo",
  "number": 791
}, {
  "name": "lunala",
  "number": 792
}, {
  "name": "nihilego",
  "number": 793
}, {
  "name": "buzzwole",
  "number": 794
}, {
  "name": "pheromosa",
  "number": 795
}, {
  "name": "xurkitree",
  "number": 796
}, {
  "name": "celesteela",
  "number": 797
}, {
  "name": "kartana",
  "number": 798
}, {
  "name": "guzzlord",
  "number": 799
}, {
  "name": "necrozma",
  "number": 800
}, {
  "name": "magearna",
  "number": 801
}, {
  "name": "marshadow",
  "number": 802
}, {
  "name": "poipole",
  "number": 803
}, {
  "name": "naganadel",
  "number": 804
}, {
  "name": "stakataka",
  "number": 805
}, {
  "name": "blacephalon",
  "number": 806
}, {
  "name": "zeraora",
  "number": 807
}]
